swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: ex10apigateway

paths:
  /:
    post:
      description: Adds an item to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: inventoryItem
        description: Inventory item to add
        schema:
          $ref: '#/definitions/InventoryItem'
      responses:
        "200":
          description: item created
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub:
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn:
              Fn::GetAtt:
                - CheckerLambda
                - Arn
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

definitions:
  InventoryItem:
    type: object
    required:
    - id
    properties:
      id:
        type: string
